Add support for yolov3-tinyu in YoloV8 series
luxonis/tools pull request #31
Opened 2023-02-17 07:30 UTC by richard-xx

[yolov3-tinyu](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/v3/yolov3-tinyu.yaml) has only two output layers, I changed the output_list to be based on num_branches.

2023-02-17 11:48 UTC, tersekmatija commented
Hey @richard-xx,

Good catch, thanks for your contribution. Adding @HonzaCuhel to quickly review the whole PR, test, approve, and deploy.

2023-02-18 07:21 UTC, HonzaCuhel requested changes
@richard-xx, nice catch! Thank you very much! There is one slight change needed

2023-02-18 07:21 UTC, HonzaCuhel commented on yolo/export_yolov8.py
> +                        output_names=["output{i+1}_yolov6r2" for i in range(self.num_branches) ],
There is missing `f` in the formatted string.
@richard-xx, could you please add f before the first double quote, so it'll be like this: `output_names=[f"output{i+1}_yolov6r2" for i in range(self.num_branches) ]`?

2023-02-18 23:32 UTC, HonzaCuhel approved these changes
@richard-xx Thank you! Seems good to me now!

2023-02-18 23:36 UTC, merged